[package]
org = "ballerinax"
name = "postgresql"
version = "@toml.version@"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/postgresql-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-@sql.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/postgresql-@driver.version@.jar"
scope = "testOnly"
