[package]
org = "ballerinax"
name = "postgresql"
version = "1.4.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "PostgreSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.1.0"

[[platform.java11.dependency]]
path = "../native/build/libs/postgresql-native-1.4.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.4.0-20220520-141600-b5a3702.jar"

[[platform.java11.dependency]]
path = "./lib/postgresql-42.3.3.jar"
scope = "testOnly"
