[package]
org = "ballerinax"
name = "postgresql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../postgresql-native/build/libs/postgresql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "postgresql-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/sql-native-@sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "sql-native"
version = "@sql.native.version@"

[[platform.java11.dependency]]
path = "./lib/postgresql-@driver.version@.jar"
artifactId = "postgresql-connector-java"
groupId = "postgresql"
scope = "testOnly"
version = "@driver.version@"
