[package]
org = "ballerinax"
name = "postgresql"
version = "0.7.0-beta.1"

[[platform.java11.dependency]]
path = "../postgresql-native/build/libs/postgresql-native-0.7.0-beta.1-SNAPSHOT.jar"
groupId = "org.ballerinalang"
artifactId = "postgresql-native"
version = "0.7.0-beta.1-SNAPSHOT"

[[platform.java11.dependency]]
path = "./lib/sql-native-0.6.0-beta.1-20210601-165800-9f5615e.jar"
groupId = "org.ballerinalang"
artifactId = "sql-native"
version = "0.6.0-beta.1-20210601-165800-9f5615e"

[[platform.java11.dependency]]
path = "./lib/postgresql-42.2.20.jar"
artifactId = "postgresql-connector-java"
groupId = "postgresql"
scope = "testOnly"
version = "42.2.20"
