resources:
  - execute_operation.yaml
  - ingress.yaml
  - postgres_deployment.yml
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: execute-operation-deployment
